### ISSUE TITLE
Unable to test with Humanoid and Snake tasks

### ISSUE THREAD

**Issue by tmparticle** [thanard/me-trpo#1]
I'd like to play me-trpo with com_humanoid_env and com_snake_env tasks, but currently some files seems lacked.
As far as I understand, snake.xml for com_snake_env and private_examples for com_humanoid_env don't exist. Could you push these files?

**Comment by thanard** [comment]
Thanks for the report. This is now fixed. Please put `vendor/mujoco_models/snake.xml` under `rllab/vendor/mujoco_models`.
