### ISSUE TITLE
How to run Humanoid task

### ISSUE THREAD

**Issue by IrisLi17** [thanard/me-trpo#3]
https://github.com/thanard/me-trpo/blob/7dad9cd91e8f259ffeaf2bdb669c84a6db3ceeaa/envs/com_humanoid_env.py#L1

Hi, I am trying to run humanoid environment but it seems that SimpleHumanoidEnv is missing. Specifically, I cannot find the file that defines the observation, cost etc. for humanoid as for other environments.

**Comment by thanard** [comment]
It's this one: https://github.com/thanard/me-trpo/blob/7dad9cd91e8f259ffeaf2bdb669c84a6db3ceeaa/envs/com_simple_humanoid_env.py
